version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      ports: 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gindb -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    image: gin-app:latest
    command: ["./main"]
    volumes:
      - .:/WD
    ports:
      - "80:8080"
    links:
      - db